import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "ContentCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={poppins.className}>
        <body className="font-poppins">
          <main> {children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
