import React from "react";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "ContentCraft",
  description: "Generated by create next app",
};

export default function Dashboardlayout({ children }) {
  return (
    <>
      <main>{children}</main>
      <Toaster />
    </>
  );
}
